### ISSUE TITLE
Issues reagarding train and export commands.

### ISSUE THREAD

**Issue by AKDURANI** [hugoycj/NeuralBaker#15]
Thanks for such an intuitive repo source. Unfortunately, I am unable to resolve these errors while using the kaggle notebook.

Isasue#1:
Command: python launch.py --config configs/bakedsdf-colmap.yaml --gpu 0 --train     dataset.root_dir=$1 \
                --resume_weights_only --resume latest
Error: AttributeError: 'Trimesh' object has no attribute 'simplify_quadratic_decimation'. 
                Did you mean: 'simplify_quadric_decimation'?
Description:    
[swscaler @ 0x5b11a40] Warning: data is not aligned! This can lead to a speed loss
Traceback (most recent call last):
  File "/kaggle/working/torch-bakedsdf/launch.py", line 130, in <module>
    main()
  File "/kaggle/working/torch-bakedsdf/launch.py", line 120, in main
    trainer.test(system, datamodule=dm)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 794, in test
    return call._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 842, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1188, in _run_stage
    return self._run_evaluate()
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1228, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 206, in run
    output = self.on_run_end()
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 180, in on_run_end
    self._evaluation_epoch_end(self._outputs)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 288, in _evaluation_epoch_end
    self.trainer._call_lightning_module_hook(hook_name, output_or_outputs)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/kaggle/working/torch-bakedsdf/systems/bakedsdf.py", line 224, in test_epoch_end
    self.export()
  File "/kaggle/working/torch-bakedsdf/systems/bakedsdf.py", line 228, in export
    mesh = self.model.export_glb(self.config.export.chunk_size)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/kaggle/working/torch-bakedsdf/models/bakedsdf.py", line 146, in export_glb
    tri_mesh = tri_mesh.simplify_quadratic_decimation(len(tri_mesh.faces) * 0.5)
AttributeError: 'Trimesh' object has no attribute 'simplify_quadratic_decimation'. Did you mean: 'simplify_quadric_decimation'?
Testing DataLoader 0: 100%|██████████| 120/120 [06:09<00:00,  3.08s/it]            
  
---------------------------------------------------------------------------------------------------------------------------------------------------  

Issue#2:                
Command: python export.py --exp_dir ./exp/${exp_name}/${trail-name}
Error: AttributeError: 'NeuSModel' object has no attribute 'export_glb'
Description:
Traceback (most recent call last):
  File "/kaggle/working/torch-bakedsdf/export.py", line 56, in <module>
    main()
  File "/kaggle/working/torch-bakedsdf/export.py", line 48, in main
    mesh = system.model.export_glb()
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(

**Comment by huahuo359** [comment]
Same question, may I ask if you have solved this issue?

**Comment by YeZibn** [comment]
> Same question, may I ask if you have solved this issue?
May I ask if your problem has been solved? I modified the prompt code, but it displayed:
ValueError: ' 'target_reduction' 'must be between 0 and 1

**Comment by YeZibn** [comment]
> Same question, may I ask if you have solved this issue?

1

**Comment by YeZibn** [comment]
> Same question, may I ask if you have solved this issue?

May I ask if your problem has been solved? I modified the prompt code, but it displayed:
ValueError: ' 'target_reduction' 'must be between 0 and 1
