### ISSUE TITLE
It appears that the Install command does not work properly

### ISSUE THREAD

**Issue by SydianAndrewChen** [hugoycj/NeuralBaker#2]
```
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
pip install -r requirements.txt
```

appears to give me result of 
```
cuda-nn/#subdirectory=bindings/torch
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch            q-build-jx3n58h2
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to c:\users\sydian\appdata\local\temp\pip-re 'C:\Users\Sydian\AppData\Local\Temp\pip-req-build-jx3n58h2'q-build-jx3n58h2                                                                              a39ce44
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ 'C:\Users\Sydian\AppData\Local\Temp\pip-req-build-jx3n58h2'
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit e02068459c4c36ba8b6fc40e312a301dca39ce44
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      C:\Users\Sydian\AppData\Local\Temp\pip-req-build-jx3n58h2\bindings/torch\setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Sydian\AppData\Local\Temp\pip-req-build-jx3n58h2\bindings/torch\setup.py", line 9, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.        
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Newly created environment through `conda`. `Python=3.10`

**Comment by hugoycj** [comment]
I apologize for the inconvenience. Before installing tiny-cuda-nn, it is necessary to install torch by running the command `pip install torch torchvision`. I have made the necessary update to the README to address this issue.
